//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOLGA_EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEES()
        {
            this.USERS = new HashSet<USERS>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_FIRST_NAME { get; set; }
        public string EMPLOYEE_SECOND_NAME { get; set; }
        public string EMPLOYEE_PATRONYMIC { get; set; }
        public string EMPLOYEE_PHONE_NUMBER { get; set; }
        public Nullable<int> EMPLOYEE_POSITION { get; set; }
        public string EMPLOYEE_DATE_OF_BIRTH { get; set; }
        public string EMPLOYEE_DATE_OF_ADDITION { get; set; }
    
        public virtual POSITIONS POSITIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS> USERS { get; set; }
    }
}
