//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOLGA_EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTS
    {
        public int PROJECT_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public string PROJECT_DISCRIPTION { get; set; }
    }
}
