//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOLGA_EAS_SIMPLE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_STAFF
    {
        public int PROJECT { get; set; }
        public int USER { get; set; }
        public string START_OF_WORK { get; set; }
        public string END_OF_WORK { get; set; }
    
        public virtual PROJECT PROJECT1 { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
