//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOLGA_EAS_SIMPLE
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.PROJECT_STAFF = new HashSet<PROJECT_STAFF>();
        }
    
        public int USER_ID { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_NAME { get; set; }
        public string USER_FIRST_NAME { get; set; }
        public string USER_SECOND_NAME { get; set; }
        public string USER_PATRONYMIC { get; set; }
        public string USER_DATE_OF_BIRTH { get; set; }
        public Nullable<int> USER_EMPLOYEE { get; set; }
        public string USER_DATE_OF_ADDITION { get; set; }
        public string USER_PASSWORD { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_STAFF> PROJECT_STAFF { get; set; }
    }
}
